## template: jinja
#cloud-config

# yum_repos:
#   salt_repo:
#     name: Salt repo for RHEL/CentOS 8 PY3
#     baseurl: https://repo.saltproject.io/py3/redhat/8/x86_64/3003
#     gpgcheck: 1
#     gpgkey: https://repo.saltproject.io/py3/redhat/8/x86_64/latest/SALTSTACK-GPG-KEY.pub
runcmd:
  - ip route add 192.168.1.0/24 via ${gateway_ip}
  - sudo rpm --import https://repo.saltproject.io/py3/redhat/8/x86_64/latest/SALTSTACK-GPG-KEY.pub
  - curl -fsSL https://repo.saltproject.io/py3/redhat/8/x86_64/3004.repo | sudo tee /etc/yum.repos.d/salt.repo
manage_resolv_conf: true
resolv_conf:
  nameservers:
    - 173.245.58.51
    - 198.41.222.173
  searchdomains:
    - internal.seymour.family
  domain: internal.seymour.family
