#cloud-config

write_files:
  - path: /etc/sysctl.d/10-ip-forwarding.conf
    content: |
      net.ipv4.ip_forward=1
yum_repos:
  salt-latest-repo:
    name: Salt repo for RHEL/CentOS 8
    baseurl: https://repo.saltproject.io/py3/redhat/8/x86_64/latest
    gpgcheck: true
    gpgkey: https://repo.saltproject.io/py3/redhat/8/x86_64/latest/SALTSTACK-GPG-KEY.pub
    skip_if_unavailable: true
# salt_minion:
#   conf:
#     master: 192.168.1.200
